# Generated by Django 2.2.2 on 2019-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciante',
            name='email',
            field=models.TextField(max_length=150),
        ),
    ]
