# Generated by Django 2.2.2 on 2019-06-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciante', '0002_auto_20190617_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciante',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='anunciante',
            name='senha',
            field=models.CharField(max_length=8),
        ),
    ]
