# Generated by Django 2.2.2 on 2019-06-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('pecas', '0001_initial'),
        ('enderecoEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusDeFinalizacao', models.CharField(max_length=7)),
                ('descricaoPeca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecas.Pecas')),
                ('enderecoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecoEntrega.EnderecoEntrega')),
                ('infoContato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
